spring:
 application:
  name: spring-boot-loggint
 output:
    ansi :
      enabled :
          detect 
 profiles:
  active:
   -dev         
---
spring:
 h2:
  console:
   enabled: true
 datasource:
    url: jdbc:h2:mem:testdb
---
#logging configuration
spring:
  output:
    ansi:
      enabled :  always
logging:
    level: 
      com:
        javatechie:
             DEBUG
---        

#FILE CONFIG
logging:
  file:
    name: application.log
  pattern:
     file: "%d{dd-MM-yyyy HH:mm:ss} | %-5level | %logger{1.} | %msg%n"
     console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} [%level] %c{1.} {%t} %m%n"
    #file: "%d[%level] %c{1.} {%t} %m%n"
